name: Tests
on:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  run-clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architectures:
          - linux/amd64
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v2.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: extractions/setup-just@v1
      - name: Setup nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: List tests
        run: cargo nextest list
      - name: Run tests
        run: cargo nextest run
